name: base
dependencies:
  conda:
    - notebook: "6.0.1"
    - jupyterhub: ""
    - jupyterlab: "1.2.3"
  pip:
  scripts:
    - one: |
        This entire block of text will be the value of the 'literal_block' key,
        with line breaks being preserved.

        The literal continues until de-dented, and the leading indentation is
        stripped.

        Any lines that are 'more-indented' keep the rest of their indentation -
        these lines will be indented by 4 spaces.
